import { ButlerItem, ButlerSourceContext, ExecutionLog, MemoryPreference, NoteCardModel, WorkflowPlan, Artifact, GmailCleanupAnalysis, OutlookUnreadAnalysis } from '../../types';
import { createButlerItem } from './butlerIntakeService';
import { interpretButlerItem } from './butlerInterpreter';
import { createWorkflowPlan } from './butlerWorkflowPlanner';
import { executePlan } from './butlerExecutionService';
import { createArtifact } from './butlerArtifactService';
import { resolveMemoryLinks } from './butlerMemoryService';
import { getTemplateHint } from './butlerTemplateService';
import { getNextStepLabel } from './butlerVerificationService';

export type ButlerOrchestrationResult = {
  item: ButlerItem;
  workflowPlan: WorkflowPlan;
  artifacts: Artifact[];
  logs: ExecutionLog[];
  nextStep: string;
};

export function runButlerRequest(input: {
  rawIntentText: string;
  sourceContext?: ButlerSourceContext[];
  notes: NoteCardModel[];
  memoryPreferences?: MemoryPreference[];
  gmailCleanupAnalysis?: GmailCleanupAnalysis | null;
  outlookUnreadAnalysis?: OutlookUnreadAnalysis | null;
  itemId?: string;
  createdAt?: number;
}): ButlerOrchestrationResult {
  const baseItem = createButlerItem({
    rawIntentText: input.rawIntentText,
    sourceContext: input.sourceContext,
    itemId: input.itemId,
    createdAt: input.createdAt
  });
  const interpretation = interpretButlerItem(baseItem);
  const interpretedItem: ButlerItem = {
    ...baseItem,
    interpretedIntent: interpretation.interpretedIntent,
    category: interpretation.category,
    confidence: interpretation.confidence,
    reviewRequirement: interpretation.reviewRequirement,
    trustTier: interpretation.trustTier,
    assumptions: interpretation.assumptions,
    uncertainties: interpretation.uncertainties,
    clarificationQuestions: interpretation.clarificationQuestions,
    status: interpretation.uncertainties.length && interpretation.category === 'custom' ? 'clarifying' : 'planned'
  };

  const plan = createWorkflowPlan(interpretedItem);
  const templatedPlan = { ...plan, templateId: plan.templateId ?? getTemplateHint(interpretedItem) };

  if (interpretedItem.status === 'clarifying') {
    const clarificationArtifact = createArtifact({
      type: 'summary',
      title: 'Clarification brief',
      body: [
        `Request: ${interpretedItem.rawIntentText}`,
        '',
        `Current interpretation: ${interpretedItem.interpretedIntent}`,
        '',
        interpretedItem.clarificationQuestions.length
          ? 'Clarifications needed:\n' + interpretedItem.clarificationQuestions.map((question) => `- ${question.prompt}`).join('\n')
          : 'Clarifications needed:\n- Add enough scope to map this request to a supported workflow.'
      ].join('\n'),
      linkedSourceIds: interpretedItem.sourceContext.flatMap((contextEntry) => contextEntry.sourceIds),
      status: 'ready_for_review',
      provenance: 'Generated by Butler while pausing at the clarification boundary.',
      changeSummary: 'Captured the current interpretation and the missing information needed to proceed.'
    });
    const clarificationLog: ExecutionLog = {
      id: crypto.randomUUID(),
      butlerItemId: interpretedItem.id,
      timestamp: Date.now(),
      actorType: 'orchestrator',
      action: 'Paused for clarification',
      result: 'awaiting_review',
      evidenceLinks: [clarificationArtifact.id],
      notes: interpretedItem.clarificationQuestions.length
        ? `Prepared ${interpretedItem.clarificationQuestions.length} clarification question${interpretedItem.clarificationQuestions.length === 1 ? '' : 's'}.`
        : 'Captured the missing context needed before planning.'
    };
    const item = {
      ...interpretedItem,
      workflowPlanId: templatedPlan.id,
      artifactIds: [clarificationArtifact.id],
      executionLogIds: [clarificationLog.id],
      memoryLinks: resolveMemoryLinks(interpretedItem, input.memoryPreferences ?? [])
    };
    return {
      item,
      workflowPlan: templatedPlan,
      artifacts: [clarificationArtifact],
      logs: [clarificationLog],
      nextStep: getNextStepLabel(item.status, item.reviewRequirement)
    };
  }

  const execution = executePlan(interpretedItem, templatedPlan, {
    notes: input.notes,
    memoryPreferences: input.memoryPreferences ?? [],
    gmailCleanupAnalysis: input.gmailCleanupAnalysis ?? null,
    outlookUnreadAnalysis: input.outlookUnreadAnalysis ?? null
  });
  const item = {
    ...execution.updatedItem,
    workflowPlanId: execution.updatedPlan.id,
    memoryLinks: resolveMemoryLinks(execution.updatedItem, input.memoryPreferences ?? []),
    reuseSignals: execution.updatedItem.reuseSignals.length
      ? execution.updatedItem.reuseSignals
      : [templatedPlan.templateId ? `Candidate template: ${templatedPlan.templateId}` : 'Candidate reusable workflow']
  };
  return {
    item,
    workflowPlan: execution.updatedPlan,
    artifacts: execution.artifacts,
    logs: execution.logs,
    nextStep: getNextStepLabel(item.status, item.reviewRequirement)
  };
}
